services:
  - type: web
    name: immath-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.api
    envVars:
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.12.10"
    plan: free
